storage:
  minio:
    endpoint: http://110.42.203.200:9000
    accessKey: quanxiaoha
    secretKey: quanxiaoha
  aliyun-oss:
    # OSS 服务的访问域名，请根据实际使用的 OSS 区域替换为对应的 endpoint
    endpoint: oss-cn-shanghai.aliyuncs.com # 改成你自己的
    # 阿里云账号的 AccessKey ID，用于身份验证
    accessKey:
    # 阿里云账号的 AccessKey Secret，用于身份验证
    secretKey: